"""platform_settings_and_missing_indexes

Real bug found live on the Render deployment: PlatformSetting
(app/models/all.py) had no Alembic migration at all -- it only ever
existed in production-shaped databases because scripts/run_local_demo.py
bootstraps its DB via Base.metadata.create_all(), which silently creates
every model's table regardless of migration history. A real `alembic
upgrade head` (what app/main.py's startup_event actually runs, and what
Render's Docker deploy does) never created platform_settings at all --
every request that touched it (e.g. GET .../auth/login's
_session_timeout_minutes lookup) crashed with a 500,
psycopg2.errors.UndefinedTable, unconditionally, immediately after any
correct-credentials login or signup.

Found by generating this migration the trustworthy way: a fresh
throwaway Postgres (Docker), `alembic upgrade head` to reach the exact
same schema state as production, then `alembic revision --autogenerate`
against the live ORM models -- not by eyeballing the model list. That
diff turned up exactly one missing table (platform_settings) plus a
handful of harmless additive index/NOT NULL drifts (indexes present on
the model but never explicitly created by an earlier migration; audit_logs
.timestamp's NOT NULL was already the model's real constraint). Nothing
here is destructive: no rows to affect in the newly-created production
DB, no column drops, no type changes.

Revision ID: 9f597d152598
Revises: 1791800000
Create Date: 2026-09-30 01:59:31.525178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9f597d152598'
down_revision: Union[str, Sequence[str], None] = '1791800000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('platform_settings',
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_by', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_index(op.f('ix_platform_settings_key'), 'platform_settings', ['key'], unique=False)
    op.create_index(op.f('ix_agent_reasoning_trace_id'), 'agent_reasoning_trace', ['id'], unique=False)
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
    op.create_index(op.f('ix_checkpoints_id'), 'checkpoints', ['id'], unique=False)
    op.create_index(op.f('ix_normalized_event_versions_id'), 'normalized_event_versions', ['id'], unique=False)
    op.create_index(op.f('ix_sparks_detected_at'), 'sparks', ['detected_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_sparks_detected_at'), table_name='sparks')
    op.drop_index(op.f('ix_normalized_event_versions_id'), table_name='normalized_event_versions')
    op.drop_index(op.f('ix_checkpoints_id'), table_name='checkpoints')
    op.alter_column('audit_logs', 'timestamp',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_agent_reasoning_trace_id'), table_name='agent_reasoning_trace')
    op.drop_index(op.f('ix_platform_settings_key'), table_name='platform_settings')
    op.drop_table('platform_settings')
    # ### end Alembic commands ###
